# ---------- Base ----------
FROM node:20-alpine AS base
WORKDIR /app

# ---------- Dev ----------
FROM base AS dev
ENV NODE_ENV=development
COPY package*.json nest-cli.json tsconfig*.json prisma ./ 
RUN npm install
COPY src ./src
EXPOSE 4000
CMD ["npm", "run", "start:dev"]

# ---------- Prod deps ----------
FROM base AS deps
COPY package*.json prisma ./
RUN npm ci

# ---------- Builder ----------
FROM base AS builder
COPY --from=deps /app/node_modules ./node_modules
COPY package*.json nest-cli.json tsconfig*.json prisma ./ 
COPY src ./src
RUN npm run build && npx prisma generate

# ---------- Runner ----------
FROM node:20-alpine AS prod
WORKDIR /app
ENV NODE_ENV=production
COPY package*.json prisma ./
RUN npm ci --omit=dev && npx prisma generate
COPY --from=builder /app/dist ./dist
EXPOSE 4000
CMD ["node", "dist/main.js"]
